name: hm_symbol
description: "HarmonyOS Symbol 华为鸿蒙系统图标库 for flutter。包含近4000个图标！"
version: 1.0.1
homepage: https://developer.huawei.com/consumer/cn/design/harmonyos-symbol/
repository: https://github.com/runoob-coder/hm_symbol_flutter
issue_tracker: https://github.com/runoob-coder/hm_symbol_flutter/issues
topics:
  - assets
  - icons
  - ui
  - harmony
  - symbol

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  code_builder: ^4.11.1
  dart_style: ^3.1.4

flutter:
   fonts:
     - family: HM Symbol
       fonts:
         - asset: fonts/HMSymbolVF.ttf
