name: hm_symbol
description: "HarmonyOS Symbol icon library for Flutter. Contains nearly 4,000 icons!"
version: 1.0.2
homepage: https://github.com/runoob-coder/hm_symbol_flutter
repository: https://github.com/runoob-coder/hm_symbol_flutter
issue_tracker: https://github.com/runoob-coder/hm_symbol_flutter/issues
topics:
  - assets
  - icons
  - ui
  - harmony
  - symbol

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  code_builder: ^4.11.1
  dart_style: ^3.1.4

flutter:
   fonts:
     - family: HM Symbol
       fonts:
         - asset: fonts/HMSymbolVF.ttf
